// 按键模拟
declare function back(): any
declare function home(): any
declare function powerDialog(): any
declare function notifications(): any
declare function quickSettings(): any
declare function recents(): any
declare function splitScreen(): any
declare function takeScreenshot(): any
declare function lockScreen(): any
declare function dismissNotificationShade(): any
declare function keyCodeHeadsetHook(): any
declare function accessibilityShortcut(): any
declare function accessibilityButtonChooser(): any
declare function accessibilityButton(): any
declare function accessibilityAllApps(): any
declare function Home(): any
declare function Back(): any
declare function Power(): any
declare function Menu(): any
declare function VolumeUp(): any
declare function VolumeDown(): any
declare function Camera(): any
declare function Up(): any
declare function Down(): any
declare function Left(): any
declare function Right(): any
declare function OK(): any
declare function Text(text): any
declare function KeyCode(code): any
